@host_api = http://localhost:4000/api
@login = user1
@password = pass123
@contentType = application/json
@temporaryJWT = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc2OTM2MDM3LCJleHAiOjE3NzY5Mzk2Mzd9.E5Sb9GXlS5cUHRE9KuWO_EIZxpeMn6Rvj_4youSthLo


### Проверка работы сервера
GET {{host_api}}/health


### Регистрация нового пользователя
# @name register
POST {{host_api}}/auth/sign-up
Content-Type: {{contentType}}

{
  "login": "newuser",
  "password": "password123"
}

### Вход в систему
# @name login
POST {{host_api}}/auth/login
Content-Type: {{contentType}}

{
  "login": "{{login}}",
  "password": "{{password}}"
}

### Получение профиля (требуется токен)
# Предварительно выполните запрос login и скопируйте токен
GET {{host_api}}/auth/me
Authorization: {{temporaryJWT}}
Content-Type: {{contentType}}


### Выход пользователя
POST {{host_api}}/auth/logout
Authorization: {{temporaryJWT}}
Content-Type: {{contentType}}


### Вход с неверными данными
POST {{host_api}}/auth/login
Content-Type: {{contentType}}

{
  "login": "wrong",
  "password": "wrong"
}

### Регистрация с неполными данными
POST {{host_api}}/auth/sign-up
Content-Type: {{contentType}}

{
   "login": "{{login}}"
}